### ISSUE TITLE
Application not starting if no credentials are found

### ISSUE THREAD

**Issue by alex88** [Netflix/asgard#612]
From the wiki on first start it should ask for AWS credentials, however trying to run the standalone version using java 7 gives:

```
java -Xmx1024M -XX:MaxPermSize=128m -jar asgard-standalone.jar
Sep 03, 2014 5:39:55 PM org.apache.coyote.AbstractProtocol init
INFO: Initializing ProtocolHandler ["http-bio-8080"]
Sep 03, 2014 5:39:55 PM org.apache.catalina.core.StandardService startInternal
INFO: Starting service Tomcat
Sep 03, 2014 5:39:55 PM org.apache.catalina.core.StandardEngine startInternal
INFO: Starting Servlet Engine: Apache Tomcat/7.0.29
Sep 03, 2014 5:39:55 PM org.apache.catalina.startup.ContextConfig getDefaultWebXmlFragment
INFO: No global web.xml found
Sep 03, 2014 5:40:27 PM org.apache.catalina.startup.TaglibUriRule body
INFO: TLD skipped. URI: http://www.springframework.org/tags is already defined
Sep 03, 2014 5:40:28 PM org.apache.catalina.core.ApplicationContext log
INFO: No Spring WebApplicationInitializer types detected on classpath
Using /Users/alessandro/.asgard as ASGARD_HOME
log4j:WARN No appenders could be found for logger (org.codehaus.groovy.grails.commons.cfg.ConfigurationHelper).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
Sep 03, 2014 5:40:29 PM org.apache.catalina.core.ApplicationContext log
INFO: Initializing Spring root WebApplicationContext
Using /Users/alessandro/.asgard as ASGARD_HOME
Sep 03, 2014 5:40:53 PM org.apache.catalina.core.StandardContext listenerStart
SEVERE: Exception sending context initialized event to listener instance of class org.codehaus.groovy.grails.web.context.GrailsContextLoaderListener
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'eurekaClientHolder': Initialization of bean failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'healthcheckService': Initialization of bean failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'serverService': Initialization of bean failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'awsAutoScalingService': Initialization of bean failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'applicationService': Initialization of bean failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'awsEc2Service': Initialization of bean failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'taskService': Initialization of bean failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'flowService': Invocation of init method failed; nested exception is com.amazonaws.AmazonClientException: Unable to load AWS credentials from any provider in the chain
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)
	at java.util.concurrent.FutureTask.run(FutureTask.java:166)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:724)
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'healthcheckService': Initialization of bean failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'serverService': Initialization of bean failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'awsAutoScalingService': Initialization of bean failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'applicationService': Initialization of bean failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'awsEc2Service': Initialization of bean failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'taskService': Initialization of bean failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'flowService': Invocation of init method failed; nested exception is com.amazonaws.AmazonClientException: Unable to load AWS credentials from any provider in the chain
	... 5 more
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'serverService': Initialization of bean failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'awsAutoScalingService': Initialization of bean failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'applicationService': Initialization of bean failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'awsEc2Service': Initialization of bean failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'taskService': Initialization of bean failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'flowService': Invocation of init method failed; nested exception is com.amazonaws.AmazonClientException: Unable to load AWS credentials from any provider in the chain
	... 5 more
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'awsAutoScalingService': Initialization of bean failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'applicationService': Initialization of bean failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'awsEc2Service': Initialization of bean failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'taskService': Initialization of bean failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'flowService': Invocation of init method failed; nested exception is com.amazonaws.AmazonClientException: Unable to load AWS credentials from any provider in the chain
	... 5 more
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'applicationService': Initialization of bean failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'awsEc2Service': Initialization of bean failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'taskService': Initialization of bean failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'flowService': Invocation of init method failed; nested exception is com.amazonaws.AmazonClientException: Unable to load AWS credentials from any provider in the chain
	... 5 more
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'awsEc2Service': Initialization of bean failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'taskService': Initialization of bean failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'flowService': Invocation of init method failed; nested exception is com.amazonaws.AmazonClientException: Unable to load AWS credentials from any provider in the chain
	... 5 more
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'taskService': Initialization of bean failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'flowService': Invocation of init method failed; nested exception is com.amazonaws.AmazonClientException: Unable to load AWS credentials from any provider in the chain
	... 5 more
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'flowService': Invocation of init method failed; nested exception is com.amazonaws.AmazonClientException: Unable to load AWS credentials from any provider in the chain
	... 5 more
Caused by: com.amazonaws.AmazonClientException: Unable to load AWS credentials from any provider in the chain
	at com.amazonaws.auth.AWSCredentialsProviderChain.getCredentials(AWSCredentialsProviderChain.java:117)
	at com.amazonaws.services.simpleworkflow.AmazonSimpleWorkflowClient.invoke(AmazonSimpleWorkflowClient.java:3161)
	at com.amazonaws.services.simpleworkflow.AmazonSimpleWorkflowClient.listDomains(AmazonSimpleWorkflowClient.java:1108)
	at com.netflix.asgard.AwsSimpleWorkflowService$6.makeRequest(AwsSimpleWorkflowService.groovy:439)
	at com.netflix.asgard.retriever.AwsResultsRetriever.retrieve(AwsResultsRetriever.groovy:48)
	at com.netflix.asgard.AwsSimpleWorkflowService.retrieveDomainsAndEnsureDomainIsRegistered(AwsSimpleWorkflowService.groovy:418)
	at com.netflix.asgard.FlowService.afterPropertiesSet(FlowService.groovy:69)
	... 5 more

Sep 03, 2014 5:40:53 PM org.apache.catalina.core.StandardContext startInternal
SEVERE: Error listenerStart
Sep 03, 2014 5:40:53 PM org.apache.catalina.core.StandardContext startInternal
SEVERE: Context [] startup failed due to previous errors
Sep 03, 2014 5:40:53 PM org.apache.catalina.core.ApplicationContext log
INFO: Closing Spring root WebApplicationContext
Sep 03, 2014 5:40:53 PM org.apache.catalina.loader.WebappClassLoader clearReferencesJdbc
SEVERE: The web application [] registered the JDBC driver [org.h2.Driver] but failed to unregister it when the web application was stopped. To prevent a memory leak, the JDBC Driver has been forcibly unregistered.
Sep 03, 2014 5:40:53 PM org.apache.coyote.AbstractProtocol start
INFO: Starting ProtocolHandler ["http-bio-8080"]
Server running. Browse to http://localhost:8080
```

from what I can see it doesn't start because the AWS credentials aren't set, right?

**Comment by schmitch** [comment]
Guys you could fix this just by creating a config file under ASGARD_HOME:
```
grails {
	awsAccounts=['YOUR_ACCOUNT_ID']
	awsAccountNames=['YOUR_ACCOUNT_ID':'prod']
}
secret {
	accessId='ACCESS_ID'
	secretKey='SECRET_ACCESS_KEY'
}
cloud {
	accountName='prod'
	publicResourceAccounts=['amazon']
}
```

**Comment by blairn** [comment]
True, but there was no documentation about what it should look like or where it should go, and the guide to installing Asgard was wrong. Still could be.

**Comment by gtmtech** [comment]
Still borked. Basically the main docs/wiki dont work for 1.5.1 obviously
