### ISSUE TITLE
Prepare Automated Deploy feature??

### ISSUE THREAD

**Issue by rroese** [Netflix/asgard#619]
Hi,

I was watching this video the other day about Asgard - here's the link:
http://www.youtube.com/watch?v=wY49LuXfwH0&t=26m45s

There is an autotemated deployment feature demoed in the video. I see the button when Asgard is deployed, but when I click the button I get to a blank page. Is this feature in the current code base. I can't see to find it /get it to work.

Thanks,
Robert

**Comment by kellermark** [comment]
I also get a progress bar and exceptions in the log. My exceptions are different.

Any ideas?

grails.web.errors.GrailsExceptionResolver    IllegalArgumentException occurred when processing request: [GET] /us-west-2/deployment/prepare/testapp
Conflicting getter definitions for property "propagateAtLaunch": com.amazonaws.services.autoscaling.model.Tag#getPropagateAtLaunch(0 params) vs com.amazonaws.services.autoscaling.model.Tag#isPropagateAtLaunch(0 params). Stacktrace follows:
java.lang.IllegalArgumentException: Conflicting getter definitions for property "propagateAtLaunch": com.amazonaws.services.autoscaling.model.Tag#getPropagateAtLaunch(0 params) vs com.amazonaws.services.autoscaling.model.Tag#isPropagateAtLaunch(0 params)
	at com.fasterxml.jackson.databind.introspect.POJOPropertyBuilder.getGetter(POJOPropertyBuilder.java:164)
	at com.fasterxml.jackson.databind.introspect.POJOPropertyBuilder.getAccessor(POJOPropertyBuilder.java:257)
	at com.fasterxml.jackson.databind.ser.BeanSerializerFactory.removeIgnorableTypes(BeanSerializerFactory.java:665)
	at com.fasterxml.jackson.databind.ser.BeanSerializerFactory.findBeanProperties(BeanSerializerFactory.java:544)
	at com.fasterxml.jackson.databind.ser.BeanSerializerFactory.constructBeanSerializer(BeanSerializerFactory.java:360)
	at com.fasterxml.jackson.databind.ser.BeanSerializerFactory.findBeanSerializer(BeanSerializerFactory.java:247)
	at com.fasterxml.jackson.databind.ser.BeanSerializerFactory.createSerializer(BeanSerializerFactory.java:198)
	at com.fasterxml.jackson.databind.ser.SerializerFactory.createSerializer(SerializerFactory.java:53)
	at com.fasterxml.jackson.databind.SerializerProvider._createUntypedSerializer(SerializerProvider.java:935)
	at com.fasterxml.jackson.databind.SerializerProvider._createAndCacheUntypedSerializer(SerializerProvider.java:892)
	at com.fasterxml.jackson.databind.SerializerProvider.findValueSerializer(SerializerProvider.java:429)
	at com.fasterxml.jackson.databind.ser.impl.PropertySerializerMap.findAndAddSerializer(PropertySerializerMap.java:38)
	at com.fasterxml.jackson.databind.ser.std.AsArraySerializerBase._findAndAddDynamic(AsArraySerializerBase.java:277)
	at com.fasterxml.jackson.databind.ser.std.CollectionSerializer.serializeContents(CollectionSerializer.java:113)
	at com.fasterxml.jackson.databind.ser.std.CollectionSerializer.serializeContents(CollectionSerializer.java:24)
	at com.fasterxml.jackson.databind.ser.std.AsArraySerializerBase.serialize(AsArraySerializerBase.java:180)
	at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:544)
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:551)
	at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:143)
	at com.fasterxml.jackson.databind.ser.std.MapSerializer.serializeFields(MapSerializer.java:391)
	at com.fasterxml.jackson.databind.ser.std.MapSerializer.serialize(MapSerializer.java:312)
	at com.fasterxml.jackson.databind.ser.std.MapSerializer.serialize(MapSerializer.java:26)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:120)
	at com.fasterxml.jackson.databind.ObjectWriter._configAndWriteValue(ObjectWriter.java:610)
	at com.fasterxml.jackson.databind.ObjectWriter.writeValueAsString(ObjectWriter.java:530)
	at com.netflix.asgard.DeploymentController.prepare(DeploymentController.groovy:227)
	at org.apache.shiro.web.servlet.AbstractShiroFilter.executeChain(AbstractShiroFilter.java:449)
	at org.apache.shiro.web.servlet.AbstractShiroFilter$1.call(AbstractShiroFilter.java:365)
	at org.apache.shiro.subject.support.SubjectCallable.doCall(SubjectCallable.java:90)
	at org.apache.shiro.subject.support.SubjectCallable.call(SubjectCallable.java:83)
	at org.apache.shiro.subject.support.DelegatingSubject.execute(DelegatingSubject.java:380)
	at org.apache.shiro.web.servlet.AbstractShiroFilter.doFilterInternal(AbstractShiroFilter.java:362)
	at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)
	at org.apache.shiro.grails.SavedRequestFilter.doFilter(SavedRequestFilter.java:55)
	at com.planetj.servlet.filter.compression.CompressingFilter.doFilter(CompressingFilter.java:270)
	at com.brandseye.cors.CorsFilter.doFilter(CorsFilter.java:65)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)

[2015-01-06 03:27:44,318] [http-bio-8080-exec-1] com.netflix.asgard.EmailerService    Sending email: [
     METHOD : GET;
     URL : /us-west-2/deployment/prepare/testapp;
     QUERY : deploymentTemplateName=CreateAndCleanUpPreviousAsg&includeEnvironment=true;
     PARAMS : [
          deploymentTemplateName : [
               CreateAndCleanUpPreviousAsg;
          ]
          includeEnvironment : [
               true;
          ]
     ]
     ATTRS : [
          charEncodingFilter.FILTERED : true;
          com.opensymphony.sitemesh.APPLIED_ONCE : true;
          com.planetj.servlet.filter.compression.AlreadyApplied : true;
          grailsWebRequest.FILTERED : true;
          hiddenHttpMethod.FILTERED : true;
          javax.servlet.forward.query_string : deploymentTemplateName=CreateAndCleanUpPreviousAsg&includeEnvironment=true;
          javax.servlet.forward.request_uri : /us-west-2/deployment/prepare/testapp;
          javax.servlet.forward.servlet_path : /us-west-2/deployment/prepare/testapp;
          org.codehaus.groovy.grails.ACTION_NAME_ATTRIBUTE : prepare;
          org.codehaus.groovy.grails.CONTROLLER_NAME_ATTRIBUTE : deployment;
          org.codehaus.groovy.grails.GRAILS_CONTROLLER_CLASS : Artefact > Deployment;
          org.codehaus.groovy.grails.GRAILS_CONTROLLER_CLASS_AVAILABLE : true;
          org.codehaus.groovy.grails.web.sitemesh.GrailsPageFilter.GSP_SITEMESH_PAGE : org.codehaus.groovy.grails.web.sitemesh.GSPSitemeshPage@206824de;
          org.codehaus.groovy.grails.WEB_REQUEST : ServletWebRequest: uri=/grails/deployment/prepare.dispatch;client=127.0.0.1;session=E48B0D579A10B224193CD3BA4C3EF766;
          org.springframework.web.servlet.DispatcherServlet.CONTEXT : org.codehaus.groovy.grails.commons.spring.GrailsWebApplicationContext@e0d0b81: startup date [Tue Jan 06 03:22:03 UTC 2015]; parent: Root WebApplicationContext;
          org.springframework.web.servlet.DispatcherServlet.FLASH_MAP_MANAGER : org.springframework.web.servlet.support.SessionFlashMapManager@f924913;
          org.springframework.web.servlet.DispatcherServlet.LOCALE_RESOLVER : org.springframework.web.servlet.i18n.SessionLocaleResolver@3e78b640;
          org.springframework.web.servlet.DispatcherServlet.THEME_RESOLVER : org.springframework.web.servlet.theme.FixedThemeResolver@2810ba8c;
          org.springframework.web.servlet.DispatcherServlet.THEME_SOURCE : org.codehaus.groovy.grails.commons.spring.GrailsWebApplicationContext@e0d0b81: startup date [Tue Jan 06 03:22:03 UTC 2015]; parent: Root WebApplicationContext;
          shiroFilter.FILTERED : true;
          urlMapping.FILTERED : true;
     ]

**Comment by grahamc** [comment]
I think the errors you are seeing are from not having VPC Subnets correctly defined: https://github.com/Netflix/asgard/wiki/VPC-Configuration

**Comment by datvikash** [comment]
i am also seeing this error, has there been any updates?

**Comment by jperry** [comment]
I have elbs and services in different subnets with the correct tags in my vpc and I have no problem with my deploys but the "prepare automated deployment" does not work.  I don't think it's because of misconfigured vpc.

**Comment by gogreen53** [comment]
Also seeing this issue with all IAM access given as listed in the wiki and following the new build instructions. However I see no errors, just the following two log lines that appear once and then never again and no log lines after that when I click the "Prepare Automated Deployment" button:

```
Jun 09, 2015 8:49:50 PM org.apache.catalina.core.ApplicationContext log
INFO: Initializing Spring FrameworkServlet 'grails-errorhandler'
```

**Comment by skord** [comment]
I have the same error as @jperry, multiple VPC's in the region, but only one has immutable_metadata tags. In that vpc, there are three similarly sized subnets with the immutable_metadata set to {'purpose':'internal', 'target':'ec2'}. 

When I go to prepare an automated deployment, the progress bar hangs around 50%, then I see the same error @jperry reported on Dec 22, 2014. The bar will permanently hang at 50%. 

If I manually create the next sequential group, there's no issues. Can do that all night and day. I've not been able to find anything out of the ordinary with the SWF setup, a quick once over shows it's connecting to the right domain and is using the right task list.

**Comment by StubbsPKS** [comment]
I am having the same problem. I built from source and added in the Pull Request from Rapid7 that added support for Frankfurt since we have instances out there that we need to manage. I assumed that had broken auto deployment since it was working before.

However, I just loaded up the app from a clone of the git repo without the Frankfurt support and it is still broken.

    [2015-09-29 11:14:50,592] com.netflix.asgard.EmailerService    Sending email: [
     METHOD : GET;
     URL : /us-east-1/deployment/prepare/asg-te-qa-prv-cat;
     QUERY : deploymentTemplateName=CreateAndCleanUpPreviousAsg&includeEnvironment=true;
     PARAMS : [
          deploymentTemplateName : [
               CreateAndCleanUpPreviousAsg;
          ]
          includeEnvironment : [
               true;
          ]
     ]
     ATTRS : [
          charEncodingFilter.FILTERED : true;
          com.opensymphony.sitemesh.APPLIED_ONCE : true;
          com.planetj.servlet.filter.compression.AlreadyApplied : true;
          env : mei;
          fullTicketLabel : Ticket;
          grailsWebRequest.FILTERED : true;
          hiddenHttpMethod.FILTERED : true;
          javax.servlet.forward.query_string : deploymentTemplateName=CreateAndCleanUpPreviousAsg&includeEnvironment=true;
          javax.servlet.forward.request_uri : /us-east-1/deployment/prepare/asg-te-qa-prv-cat;
          javax.servlet.forward.servlet_path : /us-east-1/deployment/prepare/asg-te-qa-prv-cat;
          occasion : DEFAULT;
          org.codehaus.groovy.grails.ACTION_NAME_ATTRIBUTE : prepare;
          org.codehaus.groovy.grails.CONTROLLER_NAME_ATTRIBUTE : deployment;
          org.codehaus.groovy.grails.GRAILS_CONTROLLER_CLASS : Artefact > Deployment;
          org.codehaus.groovy.grails.GRAILS_CONTROLLER_CLASS_AVAILABLE : true;
          org.codehaus.groovy.grails.web.sitemesh.GrailsPageFilter.GSP_SITEMESH_PAGE : org.codehaus.groovy.grails.web.sitemesh.GSPSitemeshPage@1f6ae5a3;
          org.codehaus.groovy.grails.WEB_REQUEST : ServletWebRequest: uri=/grails/deployment/prepare.dispatch;client=0:0:0:0:0:0:0:1;session=26BE720D80A3563FA4217A8CFCF8041B;
          org.springframework.web.servlet.DispatcherServlet.CONTEXT : org.codehaus.groovy.grails.commons.spring.GrailsWebApplicationContext@1791e53: startup date [Tue Sep 29 11:07:00 EDT 2015]; parent: Root WebApplicationContext;
          org.springframework.web.servlet.DispatcherServlet.FLASH_MAP_MANAGER : org.springframework.web.servlet.support.SessionFlashMapManager@59d9e95;
          org.springframework.web.servlet.DispatcherServlet.LOCALE_RESOLVER : org.springframework.web.servlet.i18n.SessionLocaleResolver@638eb56c;
          org.springframework.web.servlet.DispatcherServlet.THEME_RESOLVER : org.springframework.web.servlet.theme.FixedThemeResolver@2aefdf9b;
          org.springframework.web.servlet.DispatcherServlet.THEME_SOURCE : org.codehaus.groovy.grails.commons.spring.GrailsWebApplicationContext@1791e53: startup date [Tue Sep 29 11:07:00 EDT 2015]; parent: Root WebApplicationContext;
          region : us-east-1;
          regions : [
               us-east-1;
               us-west-1;
               us-west-2;
               eu-west-1;
               ap-northeast-1;
               ap-southeast-1;
               ap-southeast-2;
               sa-east-1;
          ]
          shiroFilter.FILTERED : true;
          targetUri : /us-east-1/deployment/prepare/asg-te-qa-prv-cat?deploymentTemplateName=CreateAndCleanUpPreviousAsg&includeEnvironment=true;
          ticketLabel : Ticket;
          urlMapping.FILTERED : true;
     ]
     COOKIES : [
          JSESSIONID=26BE720D80A3563FA4217A8CFCF8041B;
          region=us-east-1;
     ]
     HEADERS : [
          accept : application/json, text/plain, */*;
          accept-encoding : gzip, deflate, sdch;
          accept-language : en-US,en;q=0.8;
          connection : keep-alive;
          cookie : JSESSIONID=26BE720D80A3563FA4217A8CFCF8041B; region=us-east-1;
          host : localhost:8080;
          referer : http://localhost:8080/us-east-1/ng;
          user-agent : Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/44.0.2403.107 Safari/537.36;
     ]
     REMOTEADDR : 0:0:0:0:0:0:0:1;
     REMOTEHOST : 0:0:0:0:0:0:0:1;
     CLIENTHOST : localhost;
     CLIENTIP : 0:0:0:0:0:0:0:1;
]


    java.lang.IllegalArgumentException: Conflicting getter definitions for property "propagateAtLaunch": com.amazonaws.services.autoscaling.model.Tag#getPropagateAtLaunch(0 params) vs com.amazonaws.services.autoscaling.model.Tag#isPropagateAtLaunch(0 params)
        at com.fasterxml.jackson.databind.introspect.POJOPropertyBuilder.getGetter(POJOPropertyBuilder.java:164)
        at com.fasterxml.jackson.databind.introspect.POJOPropertyBuilder.getAccessor(POJOPropertyBuilder.java:257)
        at com.fasterxml.jackson.databind.ser.BeanSerializerFactory.removeIgnorableTypes(BeanSerializerFactory.java:665)
        at com.fasterxml.jackson.databind.ser.BeanSerializerFactory.findBeanProperties(BeanSerializerFactory.java:544)
        at com.fasterxml.jackson.databind.ser.BeanSerializerFactory.constructBeanSerializer(BeanSerializerFactory.java:360)
        at com.fasterxml.jackson.databind.ser.BeanSerializerFactory.findBeanSerializer(BeanSerializerFactory.java:247)
        at com.fasterxml.jackson.databind.ser.BeanSerializerFactory.createSerializer(BeanSerializerFactory.java:198)
        at com.fasterxml.jackson.databind.ser.SerializerFactory.createSerializer(SerializerFactory.java:53)
        at com.fasterxml.jackson.databind.SerializerProvider._createUntypedSerializer(SerializerProvider.java:935)
        at com.fasterxml.jackson.databind.SerializerProvider._createAndCacheUntypedSerializer(SerializerProvider.java:892)
        at com.fasterxml.jackson.databind.SerializerProvider.findValueSerializer(SerializerProvider.java:429)
        at com.fasterxml.jackson.databind.ser.impl.PropertySerializerMap.findAndAddSerializer(PropertySerializerMap.java:38)
        at com.fasterxml.jackson.databind.ser.std.AsArraySerializerBase._findAndAddDynamic(AsArraySerializerBase.java:277)
        at com.fasterxml.jackson.databind.ser.std.CollectionSerializer.serializeContents(CollectionSerializer.java:113)
        at com.fasterxml.jackson.databind.ser.std.CollectionSerializer.serializeContents(CollectionSerializer.java:24)
        at com.fasterxml.jackson.databind.ser.std.AsArraySerializerBase.serialize(AsArraySerializerBase.java:180)
        at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:544)
        at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:551)
        at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:143)
        at com.fasterxml.jackson.databind.ser.std.MapSerializer.serializeFields(MapSerializer.java:391)
        at com.fasterxml.jackson.databind.ser.std.MapSerializer.serialize(MapSerializer.java:312)
        at com.fasterxml.jackson.databind.ser.std.MapSerializer.serialize(MapSerializer.java:26)
        at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:120)
        at com.fasterxml.jackson.databind.ObjectWriter._configAndWriteValue(ObjectWriter.java:610)
        at com.fasterxml.jackson.databind.ObjectWriter.writeValueAsString(ObjectWriter.java:530)
        at com.netflix.asgard.DeploymentController.prepare(DeploymentController.groovy:227)
        at org.apache.shiro.web.servlet.AbstractShiroFilter.executeChain(AbstractShiroFilter.java:449)
        at org.apache.shiro.web.servlet.AbstractShiroFilter$1.call(AbstractShiroFilter.java:365)
        at org.apache.shiro.subject.support.SubjectCallable.doCall(SubjectCallable.java:90)
        at org.apache.shiro.subject.support.SubjectCallable.call(SubjectCallable.java:83)
        at org.apache.shiro.subject.support.DelegatingSubject.execute(DelegatingSubject.java:380)
        at org.apache.shiro.web.servlet.AbstractShiroFilter.doFilterInternal(AbstractShiroFilter.java:362)
        at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)
        at org.apache.shiro.grails.SavedRequestFilter.doFilter(SavedRequestFilter.java:55)
        at com.planetj.servlet.filter.compression.CompressingFilter.doFilter(CompressingFilter.java:270)
        at com.brandseye.cors.CorsFilter.doFilter(CorsFilter.java:65)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)

**Comment by binbinlau** [comment]
“com.fasterxml.jackson.core.JsonGenerationException: Null key for a Map not allowed in JSON (use a converting NullKeySerializer?) ”   some data that you get is wrong, which at least one key is null in you Map, you can check all map's value in your programe.
