### ISSUE TITLE
Application unable to deploy in tomcat getting below messages

### ISSUE THREAD

**Issue by ravikumar2000** [Netflix/asgard#726]
INFO: Initializing Spring root WebApplicationContext
Apr 20, 2017 1:37:55 AM org.apache.catalina.core.StandardContext listenerStart
SEVERE: Exception sending context initialized event to listener instance of class org.codehaus.groovy.grails.web.context.GrailsContextLoaderListener
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'pluginManager' defined in ServletContext resource [/WEB-INF/applicationContext.xml]: Invocation of init method failed; nested exception is java.lang.NullPointerException: Cannot invoke method getAt() on null object
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException: Cannot invoke method getAt() on null object
        ... 3 more

**Comment by ravikumar2000** [comment]
getting this message whenever i deploy all asgard files with differnet versions in tomcat server. Unable to start asgard 1.4,1.5 versions. 
Appreciate your quick response on this .	
FAIL - Application at context path /asgard (2) could not be started

**Comment by aleon1220** [comment]
Asgard is deprecated. You should close this isse.
